# Generated by Django 5.2.7 on 2025-10-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='solutions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
