# Generated by Django 5.2.7 on 2025-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_solution_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.CharField(choices=[('website-landing', 'Website & Landing'), ('product-design', 'Product Design'), ('custom-software', 'Custom Software'), ('process-automation', 'Process Automation'), ('web-apps', 'Web Apps'), ('it-consulting', 'IT Consulting')], max_length=100),
        ),
    ]
